apiVersion: v1
kind: Service
metadata:
  name: mydotnetapp
  namespace: prod
spec:
  selector:
    app: mydotnetapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
